### ISSUE TITLE
Create LICENSE file

### ISSUE THREAD

**Issue by gdbelvin** [jpillora/backoff#10]
Great library. Could benefit from the use of a LICENSE file in the root of the repo.
https://github.com/blog/1530-choosing-an-open-source-license

**Comment by jpillora** [comment]
https://github.com/jpillora/backoff#mit-license its in the README, though I guess a LICENSE file wouldn't hurt

**Comment by joonas-fi** [comment]
Separate license file at root:
 
- is a common convention
- keeps noise out of the README
- enables Github to summarize your license:

![image](https://cloud.githubusercontent.com/assets/630151/23175720/d8e25366-f868-11e6-9ffc-b3a1293caed4.png)
