### ISSUE TITLE
Hacking backoff

### ISSUE THREAD

**Issue by croqaz** [jpillora/backoff#14]
Hi !

Do you mind if I include the backoff.go file in one of my libraries? Obviously, I'll credit the authors and provide links to the original repo. My library is also MIT licensed.

It's fine if you don't allow that, I'll have to look for another library, but I really love this one because it's so small and easy to understand and just 1 file. I don't want to use a huge, bloated library.

Thank you !

**Comment by jpillora** [comment]
Yep! No worries, MIT = Do anything you like  :)
