### ISSUE TITLE
Addition of "hacktoberfest" topic

### ISSUE THREAD

**Issue by kishaningithub** [jpillora/backoff#23]
In my opinion this repo would attract a lot if new contributors if you can add "hacktoberfest" topic to this repository

More info - https://hacktoberfest.com/participation/#pr-mr-details

**Comment by jpillora** [comment]
what do you feel should be added this to package?

**Comment by kishaningithub** [comment]
Refactoring and regular chores if any like bumping the go mod version etc

**Comment by jpillora** [comment]
No thanks, https://www.theregister.com/AMP/2020/10/01/digitalocean_hacktoberfest_pull_request_spam/
