### ISSUE TITLE
Feature: Add thread-safety

### ISSUE THREAD

**Issue by jpillora** [jpillora/backoff#6]
See: https://github.com/jpillora/backoff/pull/5#issuecomment-206045804

@DrTall I'm yet to see a use-case where a concurrent backoff timer is required. Do you have a particular case in mind?

**Comment by DrTall** [comment]
I'm making use of the new `ForAttempt` method by sharing a single `*Backoff` object across many objects in multiple threads. In this way, the backoff settings (which are all identical) are not duplicated. But `ForAttempt` isn't thread safe today, which seems to defeat the purpose.

To be clear, I agree that the `Backoff` class as a whole is fine not being threadsafe. A user could just put a mutex around it if need be.

**Comment by keegancsmith** [comment]
This triggers the race detector, but is in fact safe. The convenience of the current way of doing things is great. I would suggest you just set all the fields in your `Backoff` struct as a work-around. Either way `ForAttempt` should be documented as not being safe for concurrent access unless you set all the fields.

**Comment by DrTall** [comment]
That's probably the best compromise considering this is not the primary use case. I'll send a pull request for the comments.
